version: "3.9"

services:
  db:
    build: build/db
    ports:
      - "35432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "./DDL:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      - POSTGRES_PASSWORD=fjord
      - POSTGRES_DB=memo_db

  app:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/opt/app
      - /opt/app/data/
    command: bundle exec ruby memoApp.rb
    links:
      - "db:database"
    depends_on:
      - db

